url: https://wangqinggo.github.io
title: Freedom
subtitle: Because it's there.
author: 王青
email: wangqinggo@gmail.com
description: "Because it's there."
date_format: "ordinal"
github: [metadata]
repository: wangqinggo/wangqinggo.github.io
encoding: UTF-8
future: true
jailed: false
theme: jekyll-theme-cayman
